version: '3'

services:
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - '8080:8080'
        volumes:
            - ./backend/.log:/app/.logs
        depends_on:
            database:
                condition: service_healthy
        env_file:
            - ./backend/.env

    database:
        image: postgres:14.7
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: bloquinho
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
