BEGIN;

CREATE TABLE IF NOT EXISTS "main"."notepad" (
	"id" UUID DEFAULT gen_random_uuid(),
	"content" CHARACTER VARYING(1000) NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY ("id")
);

COMMIT;
