BEGIN;

CREATE TABLE IF NOT EXISTS "main"."bloquinho" (
	"id" UUID DEFAULT gen_random_uuid(),
	"title" CHARACTER VARYING(50) UNIQUE NOT NULL,
	"is_public" BOOLEAN NOT NULL DEFAULT TRUE,
	"content" CHARACTER VARYING(1000) NOT NULL,
	"last_viewed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY ("id")
);

COMMIT;
