-- +migrate Up
CREATE TABLE IF NOT EXISTS "main"."bloquinho" (
	"id" UUID DEFAULT gen_random_uuid(),
	"title" CHARACTER VARYING(50) UNIQUE NOT NULL,
	"content" TEXT NOT NULL,
	"is_public" BOOLEAN NOT NULL DEFAULT TRUE,
	"extension" CHARACTER VARYING(10) NOT NULL DEFAULT 'txt',
	"last_viewed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY ("id")
);

-- +migrate Down
DROP TABLE "main"."bloquinho";
