name: CI/CD

on:
    pull_request:
    push:
        paths:
            - '.github/**'
            - 'app/**'
        branches: ['main']
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    compile:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app

        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: app/.nvmrc
                  cache: 'npm'
                  cache-dependency-path: app/package-lock.json
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Compile TypeScript
              run: npm run compile

    deploy:
        needs: compile
        runs-on: ubuntu-latest
        if: github.event_name == 'release'

        steps:
            - uses: actions/checkout@v4
            - name: Deploy
              env:
                  DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
              run: |
                  curl -X POST "$DEPLOY_URL"