name: CI

on:
    pull_request:
    push:
        paths:
            - '.github/**'
            - 'app/**'
        branches: ['main']
    workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app

        services:
            mongodb:
                image: mongo:latest
                ports:
                    - 27017:27017
            env:
                MONGO_INITDB_DATABASE: main
                MONGO_INITDB_ROOT_USERNAME: mongodb_username
                MONGO_INITDB_ROOT_PASSWORD: mongodb_password
            options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5

        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.11.0'
                  cache: 'npm'
                  cache-dependency-path: app/package-lock.json
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Compile TypeScript
              run: npm run compile
            - name: Build test
              run: npm run build