name: Backend CD

on:
    push:
        paths:
            - '.github/**'
            - 'backend/**'
        branches: ['main']
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Docker build and push
              id: build
              uses: cloudposse/github-action-docker-build-push@1.13.0
              with:
                  build-args: |
                      COMMIT_HASH=${{ github.sha }}
                  workdir: ./backend
                  registry: registry.hub.docker.com
                  organization: nidib
                  repository: bloquinho-api
                  login: '${{ secrets.DOCKER_USERNAME }}'
                  password: '${{ secrets.DOCKER_PASSWORD }}'
                  platforms: linux/amd64
            - name: Trigger deploy
              run: |
                curl -X 'POST' \
                '${{ secrets.DEPLOY_URL }}' \
                -H 'accept: application/json' \
                -H 'Content-Type: application/json' \
                -H 'Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}' \
                -d '{
                    "applicationId": "${{ secrets.DEPLOY_APP_ID }}"
                }'
