name: CI

on:
    pull_request:
    push:
        paths:
            - '.github/**'
            - 'app/**'
        branches: ['main']
    workflow_dispatch:

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app

        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.11.0'
                  cache: 'npm'
                  cache-dependency-path: app/package-lock.json
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Compile TypeScript
              run: npm run compile