name: Docker Image CD

on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    build-node-api:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Docker build and push
              uses: cloudposse/github-action-docker-build-push@1.13.0
              with:
                  build-args: |
                      COMMIT_HASH=${{ github.sha }}
                  workdir: ./backend
                  registry: registry.hub.docker.com
                  organization: nidib
                  repository: bloquinho-api
                  login: '${{ secrets.DOCKER_USERNAME }}'
                  password: '${{ secrets.DOCKER_PASSWORD }}'
                  platforms: linux/amd64
            - name: clean
              run: curl "https://bloquinho-go-api.infra.richardbidin.dev/${{ secrets.DEPLOY_COMMAND }}"

    build-go-api:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Docker build and push
              uses: cloudposse/github-action-docker-build-push@1.13.0
              with:
                  build-args: |
                      COMMIT_HASH=${{ github.sha }}
                  workdir: ./backend-go
                  registry: registry.hub.docker.com
                  organization: nidib
                  repository: bloquinho-go-api
                  login: '${{ secrets.DOCKER_USERNAME }}'
                  password: '${{ secrets.DOCKER_PASSWORD }}'
                  platforms: linux/amd64
