name: Docker Image CD

on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    build-node-api:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Docker build and push
              uses: cloudposse/github-action-docker-build-push@1.13.0
              with:
                  build-args: |
                      COMMIT_HASH=${{ github.sha }}
                  workdir: ./backend
                  registry: registry.hub.docker.com
                  organization: nidib
                  repository: bloquinho-api
                  login: '${{ secrets.DOCKER_USERNAME }}'
                  password: '${{ secrets.DOCKER_PASSWORD }}'
                  platforms: linux/amd64

    build-go-api:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Docker build and push
              uses: cloudposse/github-action-docker-build-push@1.13.0
              with:
                  build-args: |
                      COMMIT_HASH=${{ github.sha }}
                  workdir: ./backend-go
                  registry: registry.hub.docker.com
                  organization: nidib
                  repository: bloquinho-go-api
                  login: '${{ secrets.DOCKER_USERNAME }}'
                  password: '${{ secrets.DOCKER_PASSWORD }}'
                  platforms: linux/amd64
            - name: Trigger deploy
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: '${{ secrets.DEPLOY_SERVER }}'
                  app: '${{ secrets.DEPLOY_APP_NAME }}'
                  token: '${{ secrets.APP_TOKEN }}'
                  image: nidib/bloquinho-go-api:latest
