name: Backend CI

on:
    pull_request:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend-go

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_DB: bloquinho_tests
                    POSTGRES_USER: ci
                    POSTGRES_PASSWORD: ci
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.22.0'
            - name: Compile
              run: make compile
            - name: Test
              run: make test
              env:
                  TEST_POSTGRES_URL: postgres://ci:ci@127.0.0.1:5432/bloquinho_tests?sslmode=disable&application_name=go-api-tests
